FROM oven/bun:1.1.21-alpine

WORKDIR /app
COPY .env index.html tsconfig.json tsconfig.node.json vite.config.ts bunfig.toml \
    /app/

COPY package.json bun.lockb ./
RUN bun install

EXPOSE 3000
CMD ["bun", "run", "dev"]
