FROM oven/bun:1.0.26-alpine

WORKDIR /app
COPY .env index.html tsconfig.json tsconfig.node.json vite.config.ts \
    .eslintrc.cjs .prettierrc.cjs bunfig.toml \
    /app/

COPY package.json bun.lockb ./
RUN bun install

EXPOSE 3000
CMD ["bun", "run", "dev"]
