default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
        exclude: "\\.json$"
      - id: trailing-whitespace
