version: "3.9"

services:
  database:
    image: postgres:16.1-alpine3.19
    volumes:
      - database-volume:/var/lib/postgresql/data
    container_name: database
    restart: always
    env_file:
      - .env.database

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env.database
      - backend/.env.prod

  gcloud-config:
    scale: 0
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli
    container_name: gcloud-config

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stop_grace_period: 1s
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.eslintrc.cjs:/app/.eslintrc.cjs
      - ./frontend/.prettierrc.cjs:/app/.prettierrc.cjs

    restart: always
    env_file:
      - frontend/.env

volumes:
  database-volume:
