version: "3.9"

services:
  database:
    image: postgres:16.1-alpine3.19
    volumes:
      - internhub-db:/var/lib/postgresql/data
    container_name: database
    restart: always
    env_file:
      - .env.database

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    env_file:
      - .env.database
      - backend/.env
    depends_on:
      - database
    restart: always
    volumes:
      - ./backend/src:/app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    stop_grace_period: 1s
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    env_file:
      - frontend/.env

volumes:
  internhub-db:
