FROM python:3.12.4-alpine3.19

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN pip install --upgrade pip && pip install pipenv
COPY Pipfile Pipfile.lock ./
RUN pipenv install --dev --system --ignore-pipfile

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
