FROM python:3.12.4-alpine3.19

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements-dev.txt ./
RUN pip install --upgrade pip && pip install uv
RUN uv pip install --system -r requirements-dev.txt

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
