[tool.mypy]
exclude = ["_env", "migrations"]
ignore_missing_imports = true
python_version = "3.12"
strict_optional = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "_conf.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "_conf.settings"
python_files = ["*/test*.py"]

[tool.ruff]
exclude = ["_env", "migrations"]
line-length = 120
target-version = "py312"
src            = ["./src"]


    [tool.ruff.lint]
    ignore = [
        "D100",
        "D101",
        "D102",
        'D103',
        "D104",
        "D105",
        "D106",
        "D107",
        "D203",
        "D212",
        "ANN002",
        "ANN003",
        "ANN101",
        "ARG002",
        "PGH003",
        "PT009",
        "COM812",
        "ISC001",
        "RUF012",
        "TRY003",
        "G004",
        "EM101",
        "FBT001",
    ]
    select = ["ALL"]
