[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.MASTER]
load-plugins = "pylint_django"

[tool.pylint.pylint_django]
django-settings-module = "_conf.settings"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = "C0114,C0115,C0116,W0613"


[tool.mypy]
strict_optional = true
ignore_missing_imports = true
[plugins]
mypy_django_plugin.main = { "django_settings_module" = "_conf.settings" }
mypy_drf_plugin.main = {}
